# Generated by Django 2.0.5 on 2021-03-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupan',
            new_name='Coupon',
        ),
    ]
